Remove .idea
submariner-io/enhancements pull request #205
Opened 2023-07-06 09:14 UTC by skitt

This shouldn't have been committed to the repository.

2023-07-06 09:25 UTC, vthapar requested changes
Would be good to also create `.gitignore` with `.idea`, `.project` and `.settings`

2023-07-06 10:14 UTC, skitt commented
> Would be good to also create `.gitignore` with `.idea`, `.project` and `.settings`

No: https://github.com/submariner-io/submariner/pull/2175#pullrequestreview-1206584647

2023-07-06 11:13 UTC, vthapar approved these changes

2023-07-10 07:17 UTC, maayanf24 approved these changes

2023-07-10 15:25 UTC, dfarrell07 approved these changes

2023-07-30 10:25 UTC, tpantelis approved these changes

2023-07-30 10:25 UTC, merged