OVN_Kubernetes IPv6 support
submariner-io/enhancements pull request #241
Opened 2024-12-24 23:13 UTC by aswinsuryan

OVN_Kubernetes IPv6 support

2024-12-26 07:20 UTC, sridhargaddam commented on submariner/IPV6-OVN.md
> +# **Submariner Enhancement for IPv6 Support**
Since this is OVN specific, probably we can update the sentence to

```suggestion
# **Submariner OVN CNI Enhancement for IPv6 Support**
```

2024-12-26 07:20 UTC, sridhargaddam commented on submariner/IPV6-OVN.md
> +[IPv6 Datapath Enhancements](https://github.com/submariner-io/enhancements/blob/devel/submariner/IPV6-datapath.md)
Better to use relative url (rather than full URL)

2024-12-26 07:20 UTC, sridhargaddam commented on submariner/IPV6-OVN.md
> +The next hop will be the interface IP of ovn-k8s-mp0 interface, which is expected
When we create the GatewayRoute and NonGatewayRoute CRs, we are essentially programming OVN Openflow pipeline and will be using the GENEVE tunnels already created by OVN itself for both v4 and v6 traffic right?

2024-12-26 07:20 UTC, sridhargaddam commented on submariner/IPV6-OVN.md
> +---
work items?

2024-12-26 07:20 UTC, sridhargaddam commented on submariner/IPV6-OVN.md
> +```plaintext
Maybe you can add a small note explaining what this section is about.

2024-12-31 12:51 UTC, yboaron commented on submariner/IPV6-OVN.md
> +this to support IPV6 addresses as well.
Does OVN_handler also need to be changed to support IPV6/dual-stack?

2024-12-31 13:00 UTC, yboaron commented on submariner/IPV6-OVN.md
> +apiVersion: submariner.io/v1alpha1
Do you think we should create GatewayRoute CR for each IP family?

2025-01-02 11:22 UTC, sridhargaddam commented on submariner/IPV6-OVN.md
> +apiVersion: submariner.io/v1alpha1
Looking at the sample example below, i assume that we will use only a single GatewayRoute (one for each remote endpoint) that has both the CIDRs in it.

2025-01-07 18:03 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +# **Submariner Enhancement for IPv6 Support**
Done.

2025-01-07 18:04 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +The next hop will be the interface IP of ovn-k8s-mp0 interface, which is expected
Yes.

2025-01-07 18:04 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +---
Added

2025-01-07 18:04 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +```plaintext
Done.

2025-01-07 18:05 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +apiVersion: submariner.io/v1alpha1
Now I changed it to two routes.

2025-01-07 18:10 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +this to support IPV6 addresses as well.
The IPV6 host networking rules needs to be added similar to other CNI, IIUC , it is covered in the main proposal. Should we add it here?

2025-01-07 20:04 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +[IPv6 Datapath Enhancements](https://github.com/submariner-io/enhancements/blob/devel/submariner/IPV6-datapath.md)
Done.

2025-01-16 09:15 UTC, yboaron commented on submariner/IPV6-OVN.md
> +this to support IPV6 addresses as well.
Correct, it is covered in the main proposal

2025-01-16 09:17 UTC, yboaron commented on submariner/IPV6-OVN.md
> +the gateway and non-gateway nodes to direct the traffic to the remote cluster.
Maybe we need to rephrase this sentence?

2025-01-16 09:34 UTC, yboaron commented on submariner/IPV6-OVN.md
> +The GatewayRoute will now create a new CR for with  the IPV6 next hops and
I assume we want to  create GatewayRoute,NonGatewayRoute CRs per remote endpoint IP family only if this IP family is supported by local-cluster.

2025-01-20 22:03 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +The GatewayRoute will now create a new CR for with  the IPV6 next hops and
We check this at the time of join right? Do we need another check here?

2025-01-20 22:12 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +the gateway and non-gateway nodes to direct the traffic to the remote cluster.
Done , changed to driver instead of handler.

2025-01-21 03:46 UTC, tpantelis requested changes

2025-01-21 03:46 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +the gateway and non-gateway nodes to direct the traffic to the remote cluster.
```suggestion
the gateway and non-gateway nodes to the remote cluster.
```

2025-01-21 03:46 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +The GatewayRoute will now create a new CR for with  the IPV6 next hops and
```suggestion
A GatewayRoute CR will be created with the IPV6 next hops and
```

2025-01-21 03:46 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +IPV6 remote CIDRs for a dual-stack environment along with the existing IPv4 CIDR.
```suggestion
IPV6 remote CIDRs for a dual-stack environment in addition to the IPv4 GatewayRoute.
```

2025-01-21 03:46 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +For Ipv6 only there will be only the IPV6 CR
```suggestion
For IPv6. only an IPV6 GatewayRoute will be created.
```

2025-01-21 03:46 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +The NonGatewayRoute will follow the same pattern as GatewayRoute and will create a new CR
```suggestion
The NonGatewayRoute will follow the same pattern as GatewayRoute with the creation of a new CR
```

2025-01-21 07:16 UTC, yboaron commented on submariner/IPV6-OVN.md
> +The GatewayRoute will now create a new CR for with  the IPV6 next hops and
> We check this at the time of join right? Do we need another check here?

Yep, we verify that we can create at least one tunnel between two clusters.

Assuming the following use case:
Cluster 1 is IPV4
Cluster2 is dual stack

The validation is green for this case.
How many GatewayRoute,NonGatewayRoute CRs should be created in Cluster1 to route traffic to Cluster2?

Do you see any point in creating GatewayRoute,NonGatewayRoute for IPV6?

2025-01-21 18:26 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +IPV6 remote CIDRs for a dual-stack environment along with the existing IPv4 CIDR.
Rephrased.

2025-01-21 18:26 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +For Ipv6 only there will be only the IPV6 CR
Done.

2025-01-21 18:26 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +The NonGatewayRoute will follow the same pattern as GatewayRoute and will create a new CR
Done.

2025-01-21 18:27 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +The GatewayRoute will now create a new CR for with  the IPV6 next hops and
Done.

2025-01-22 08:37 UTC, yboaron commented on submariner/IPV6-OVN.md
> +At present the routes are only programmed for IPv4 for addresses. We need to enhance
```suggestion
At present the routes are only programmed for IPv4 addresses. We need to enhance
```

2025-01-22 14:01 UTC, tpantelis requested changes

2025-01-22 14:01 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +In the case of a dual-stack environment a CR will be create for both IPv4 and Ipv6 addresses.
```suggestion
In the case of a dual-stack environment a CR will be created for both IPv4 and Ipv6 addresses.
```

2025-01-22 14:01 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +For IPv6, only an IPV6 GatewayRoute will be created.
```suggestion
For IPv6, only an IPv6 GatewayRoute will be created.
```

2025-01-22 14:01 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +to have both IPv4 and IPV6 IPs in the case of dual-stack environments.
```suggestion
to have both IPv4 and IPv6 IPs in the case of dual-stack environments.
```

2025-01-22 14:01 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +for IPV6. The nexthops will be the transit switch IP of the gateway node.
```suggestion
for IPv6. The nexthops will be the transit switch IP of the gateway node.
```

2025-01-22 14:01 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +The GatewayRoute Handler should be aware of the IPV6 address that can be present in the CR
```suggestion
The GatewayRoute Handler should be aware of the IPv6 address that can be present in the CR
```

2025-01-22 14:01 UTC, tpantelis commented on submariner/IPV6-OVN.md
> +The NonGatewayRoute Handler should be aware of the IPV6 address that can be present in the CR
```suggestion
The NonGatewayRoute Handler should be aware of the IPv6 address that can be present in the CR
```

2025-01-23 03:34 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +At present the routes are only programmed for IPv4 for addresses. We need to enhance
Done.

2025-01-23 03:34 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +In the case of a dual-stack environment a CR will be create for both IPv4 and Ipv6 addresses.
Done.

2025-01-23 03:34 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +For IPv6, only an IPV6 GatewayRoute will be created.
Done.

2025-01-23 03:34 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +to have both IPv4 and IPV6 IPs in the case of dual-stack environments.
Done.

2025-01-23 03:35 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +for IPV6. The nexthops will be the transit switch IP of the gateway node.
Done.

2025-01-23 03:35 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +The GatewayRoute Handler should be aware of the IPV6 address that can be present in the CR
Done.

2025-01-23 03:35 UTC, aswinsuryan commented on submariner/IPV6-OVN.md
> +The NonGatewayRoute Handler should be aware of the IPV6 address that can be present in the CR
Done.

2025-01-23 09:47 UTC, yboaron approved these changes

2025-01-23 13:33 UTC, tpantelis approved these changes

2025-01-23 13:33 UTC, merged