Add template for epic
submariner-io/enhancements pull request #44
Opened 2021-10-27 13:58 UTC by maayanf24

Add GitHub Issue template for a new epic, based on
the Definition of Done

Signed-off-by: Maayan Friedman <maafried@redhat.com>

2021-10-27 13:59 UTC, Jaanki approved these changes

2021-10-27 14:28 UTC, tpantelis requested changes

2021-10-27 14:28 UTC, tpantelis commented on .github/ISSUE_TEMPLATE/epic.md
> +make sure you have an item to cover all relevant topics from DoD checklist: -->
Perhaps we should move this section after.

```suggestion
## Work Items
<!-- Add work items here. 
Make sure you have item(s) to cover all relevant topics from the checklist above: -->
```

2021-10-27 14:28 UTC, tpantelis commented on .github/ISSUE_TEMPLATE/epic.md
> +## EPIC Description
```suggestion
## Epic Description
```

2021-10-28 08:07 UTC, aswinsuryan approved these changes

2021-10-28 09:19 UTC, nyechiel reviewed
Thanks for putting this together, @maayanf24. I added a few questions/suggestions inline. 

One additional thing that I think worth discussing (and was brought by @sridhargaddam, @vthapar and @mkolesnik in the past) - is where do we want Epics to live? i.e is there a consensus that all epics should go under the enhancements repo only (and therefore this template should only be available there)?

2021-10-28 09:19 UTC, nyechiel commented on .github/ISSUE_TEMPLATE/epic.md
> +about: Add an epic issue to the Submariner project
```suggestion
about: Add an epic issue template to the Submariner project
```

2021-10-28 09:19 UTC, nyechiel commented on .github/ISSUE_TEMPLATE/epic.md
> +<!-- Please only use this template for submitting epic requests -->
Can you add a description of what is an epic? Something like: "Epics contain features or other work items that help deliver on a specific initiative. Epics are a helpful way to identify and organize the work."

2021-10-28 09:19 UTC, nyechiel commented on .github/ISSUE_TEMPLATE/epic.md
> +* [ ] The acceptance criteria met
What are the acceptance criteria?

2021-10-28 09:19 UTC, nyechiel commented on .github/ISSUE_TEMPLATE/epic.md
> +* [ ] Deployed using cloud-prepare+subctl
What about Helm?

2021-10-28 09:19 UTC, nyechiel commented on .github/ISSUE_TEMPLATE/epic.md
> +
Metrics?

2021-10-28 09:29 UTC, mkolesnik commented on .github/ISSUE_TEMPLATE/epic.md
> +about: Add an epic issue to the Submariner project
Your suggestion doesn't make sense :)

This is the template, the text is what you'll see on GH.

2021-10-28 09:29 UTC, mkolesnik commented on .github/ISSUE_TEMPLATE/epic.md
> +Why is this needed:
```suggestion
<!-- Describe why is this work needed and what needs to be done -->
```

2021-10-28 09:29 UTC, mkolesnik commented on .github/ISSUE_TEMPLATE/epic.md
> +* [ ] The acceptance criteria met
I think this refers to the block in L13

2021-10-28 10:01 UTC, nyechiel commented on .github/ISSUE_TEMPLATE/epic.md
> +about: Add an epic issue to the Submariner project
Oh right, please ignore :)

2021-10-31 12:08 UTC, tpantelis approved these changes

2021-10-31 15:19 UTC, sridhargaddam approved these changes

2021-11-01 06:13 UTC, nyechiel approved these changes

2021-11-01 06:15 UTC, nyechiel commented
> Thanks for putting this together, @maayanf24. I added a few questions/suggestions inline.
> 
> One additional thing that I think worth discussing (and was brought by @sridhargaddam, @vthapar and @mkolesnik in the past) - is where do we want Epics to live? i.e is there a consensus that all epics should go under the enhancements repo only (and therefore this template should only be available there)?

@maayanf24 any thoughts on this?

2021-11-01 06:43 UTC, sridhargaddam commented
> > Thanks for putting this together, @maayanf24. I added a few questions/suggestions inline.
> > One additional thing that I think worth discussing (and was brought by @sridhargaddam, @vthapar and @mkolesnik in the past) - is where do we want Epics to live? i.e is there a consensus that all epics should go under the enhancements repo only (and therefore this template should only be available there)?
> 
> @maayanf24 any thoughts on this?

I vote for having all the epics in the enhancements repo. It will make it easy to locate the EPICs which otherwise can be spread across different components and could be hard to trace while searching in the future.

2021-11-02 07:21 UTC, sridhargaddam commented
As discussed over the slack, I'm merging this PR so that people can start using the template for the EPICs. If there are any further comments, let's push an additional PR to make changes.

2021-11-02 07:22 UTC, merged